version: '3'
 
services:
  postgres:
    image: "postgres:bookworm"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: tc
      POSTGRES_USER: tc
      POSTGRES_PASSWORD: tc
   
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres

